---
- name: Install HTTP in Rhel
  hosts: all
  become: true
  tasks:
   - name: Install httpd in RHEL
     yum:
      name: httpd
      state: installed
     when: ansible_os_family == "RedHat"
     notify: start httpd service
    
   - name: Install Apache in Ubuntu
     apt:
        name: apache2
        state: present
        update_cache: yes
     when: ansible_os_family == "Debian"

   - name: start apache
     service:
        name: apache2
        state: started
     when: ansible_os_family == "Debian"

  handlers:
   - name: start httpd service
     service:
       name: httpd
       state: started
     when: ansible_os_family == "RedHat"
