---
- name: Dlink Per Port VLAN Configuration
  hosts: all
  gather_facts: false

  tasks:

    - name: Configuring "{{inventory_hostname}}"
       include_tasks: {{item.taskfile}}
       run_once: true
       when: inventory_hostname == '{{item.host}}'
      with_items:
              - { taskfile: l1-as1.yml, host: 7989-l1-as1 }
              - { taskfile: l1-as2.yml, host: 7989-l1-as2 }
              - { taskfile: l1-as3.yml, host: 7989-l1-as3 }
              - { taskfile: l1-as4.yml, host: 7989-l1-as4 }
              - { taskfile: l1-as5.yml, host: 7989-l1-as5 }
              - { taskfile: l1-as6.yml, host: 7989-l1-as6 }
              - { taskfile: l1-as7.yml, host: 7989-l1-as7 }
              - { taskfile: l1-as8.yml, host: 7989-l1-as8 }
              - { taskfile: l1-as9.yml, host: 7989-l1-as9 }
              - { taskfile: l1-as10.yml, host: 7989-l1-as10 }
              - { taskfile: l1-as11.yml, host: 7989-l1-as11 }
              - { taskfile: l1-as12.yml, host: 7989-l1-as12 }
              - { taskfile: l1-as13.yml, host: 7989-l1-as13 }
              - { taskfile: l1-as14.yml, host: 7989-l1-as14 }
              - { taskfile: l1-as15.yml, host: 7989-l1-as15 }
              - { taskfile: l1-as16.yml, host: 7989-l1-as16 }


      
      register: print_output

    -  debug: var=print_output

    - name: run commands that require answering a prompt
      ios_command:
       commands:
       - command: 'copy running-config startup-config'
         prompt: 'Destination filename startup-config?'
         answer: 'y'


      register: print_output
    -  debug: var=print_output
