---
- name: Backup show version and other user level commands
  hosts: l1-as1
  gather_facts: false
  connection: local

  tasks:
    - name: check port security
      ios_config:
        commands:
          - vlan 100
          - vlan 200  

      register: print_output

    -  debug: var=print_output.stdout_lines

    


# Description:
# Use the ios commands module to get show version information and show interfaces information. 
# These are user mode commands.
# Save the output to files
# http://docs.ansible.com/ansible/latest/ios_command_module.html

# Commands to run: 
#1) ansible-playbook shver2.yml -u david -k

