---
- name: Save Configuratio
  hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Save Configuration
      ios_config:
        authorize: yes
        save: yes
       
          
      register: print_output

    -  debug: var=print_output

