---

    - name: Creating Vlans for AS14
      ios_config:
        lines:
          - vlan 2401-2422

      register: print_output

    -  debug: var=print_output

    - name: Access port configuration
      ios_config:
        parents: "interface ethernet 1/0/{{item.port}}"
        lines:
           - switchport mode access     
           - "switchport access vlan {{item.vlan}}"
           
      with_items:
           - { port: 1, vlan: 2401 }       
           - { port: 2, vlan: 2402 }       
           - { port: 3, vlan: 2403 }       
           - { port: 4, vlan: 2404 }       
           - { port: 5, vlan: 2405 }       
           - { port: 6, vlan: 2406 }       
           - { port: 7, vlan: 2407 }       
           - { port: 8, vlan: 2408 }       
           - { port: 9, vlan: 2409 }       
           - { port: 10, vlan: 2410 }       
           - { port: 11, vlan: 2411 }       
           - { port: 12, vlan: 2412 }       
           - { port: 13, vlan: 2413 }       
           - { port: 14, vlan: 2414 }       
           - { port: 15, vlan: 2415 }       
           - { port: 16, vlan: 2416 }       
           - { port: 17, vlan: 2417 }       
           - { port: 18, vlan: 2418 }       
           - { port: 19, vlan: 2419 }       
           - { port: 20, vlan: 2420 }       
           - { port: 21, vlan: 2421 }       
           - { port: 22, vlan: 2422 }       
              
      
      register: print_output

    -  debug: var=print_output

    - name: run commands that require answering a prompt
      ios_command:
       commands:
       - command: 'copy running-config startup-config'
         prompt: 'Destination filename startup-config?'
         answer: 'y'


      register: print_output
    -  debug: var=print_output
