---

    - name: Creating Vlans for AS3
      ios_config:
        lines:
          - vlan 1301-1322

      register: print_output

    -  debug: var=print_output

    - name: Access port configuration
      ios_config:
        parents: "interface ethernet 1/0/{{item.port}}"
        lines:
           - switchport mode access     
           - "switchport access vlan {{item.vlan}}"
           
      with_items:
           - { port: 1, vlan: 1301 }       
           - { port: 2, vlan: 1302 }       
           - { port: 3, vlan: 1303 }       
           - { port: 4, vlan: 1304 }       
           - { port: 5, vlan: 1305 }       
           - { port: 6, vlan: 1306 }       
           - { port: 7, vlan: 1307 }       
           - { port: 8, vlan: 1308 }       
           - { port: 9, vlan: 1309 }       
           - { port: 10, vlan: 1310 }       
           - { port: 11, vlan: 1311 }       
           - { port: 12, vlan: 1312 }       
           - { port: 13, vlan: 1313 }       
           - { port: 14, vlan: 1314 }       
           - { port: 15, vlan: 1315 }       
           - { port: 16, vlan: 1316 }       
           - { port: 17, vlan: 1317 }       
           - { port: 18, vlan: 1318 }       
           - { port: 19, vlan: 1319 }       
           - { port: 20, vlan: 1320 }       
           - { port: 21, vlan: 1321 }       
           - { port: 22, vlan: 1322 }       
              
      
      register: print_output

    -  debug: var=print_output

    - name: run commands that require answering a prompt
      ios_command:
       commands:
       - command: 'copy running-config startup-config'
         prompt: 'Destination filename startup-config?'
         answer: 'y'


      register: print_output
    -  debug: var=print_output
