---

    - name: Creating Vlans for AS13
      ios_config:
        lines:
          - vlan 1101-1122

      register: print_output

    -  debug: var=print_output

    - name: Access port configuration
      ios_config:
        parents: "interface ethernet 1/0/{{item.port}}"
        lines:
           - switchport mode access     
           - "switchport access vlan {{item.vlan}}"
           
      with_items:
           - { port: 1, vlan: 1101 }       
           - { port: 2, vlan: 1102 }       
           - { port: 3, vlan: 1103 }       
           - { port: 4, vlan: 1104 }       
           - { port: 5, vlan: 1105 }       
           - { port: 6, vlan: 1106 }       
           - { port: 7, vlan: 1107 }       
           - { port: 8, vlan: 1108 }       
           - { port: 9, vlan: 1109 }       
           - { port: 10, vlan: 1110 }       
           - { port: 11, vlan: 1111 }       
           - { port: 12, vlan: 1112 }       
           - { port: 13, vlan: 1113 }       
           - { port: 14, vlan: 1114 }       
           - { port: 15, vlan: 1115 }       
           - { port: 16, vlan: 1116 }       
           - { port: 17, vlan: 1117 }       
           - { port: 18, vlan: 1118 }       
           - { port: 19, vlan: 1119 }       
           - { port: 20, vlan: 1120 }       
           - { port: 21, vlan: 1121 }       
           - { port: 22, vlan: 1122 }       
              
      
      register: print_output

    -  debug: var=print_output

    - name: run commands that require answering a prompt
      ios_command:
       commands:
       - command: 'copy running-config startup-config'
         prompt: 'Destination filename startup-config?'
         answer: 'y'


      register: print_output
    -  debug: var=print_output
