---

    - name: Creating Vlans for AS16
      ios_config:
        lines:
          - vlan 2601-2622

      register: print_output

    -  debug: var=print_output

    - name: Access port configuration
      ios_config:
        parents: "interface ethernet 1/0/{{item.port}}"
        lines:
           - switchport mode access     
           - "switchport access vlan {{item.vlan}}"
           
      with_items:
           - { port: 1, vlan: 2601 }       
           - { port: 2, vlan: 2602 }       
           - { port: 3, vlan: 2603 }       
           - { port: 4, vlan: 2604 }       
           - { port: 5, vlan: 2605 }       
           - { port: 6, vlan: 2606 }       
           - { port: 7, vlan: 2607 }       
           - { port: 8, vlan: 2608 }       
           - { port: 9, vlan: 2609 }       
           - { port: 10, vlan: 2610 }       
           - { port: 11, vlan: 2611 }       
           - { port: 12, vlan: 2612 }       
           - { port: 13, vlan: 2613 }       
           - { port: 14, vlan: 2614 }       
           - { port: 15, vlan: 2615 }       
           - { port: 16, vlan: 2616 }       
           - { port: 17, vlan: 2617 }       
           - { port: 18, vlan: 2618 }       
           - { port: 19, vlan: 2619 }       
           - { port: 20, vlan: 2620 }       
           - { port: 21, vlan: 2621 }       
           - { port: 22, vlan: 2622 }       
              
      
      register: print_output

    -  debug: var=print_output

    - name: run commands that require answering a prompt
      ios_command:
       commands:
       - command: 'copy running-config startup-config'
         prompt: 'Destination filename startup-config?'
         answer: 'y'


      register: print_output
    -  debug: var=print_output
